PHP_IV_SERIES="7.0"
PHP_IV_VERSION="7.0.33"
PHP_IV_SOURCE_ARCHIVE="php-7.0.33.tar.xz"
PHP_IV_SOURCE_URL="https://www.php.net/distributions/php-7.0.33.tar.xz"
PHP_IV_SOURCE_SHA256=""
PHP_IV_SOURCE_DIR="php-7.0.33"
PHP_IV_SUPPORT_TIER="legacy"
PHP_IV_INSTALLABLE="0"
PHP_IV_SUPPORTED_PLATFORMS="linux-x86_64 linux-arm64 macos-x86_64"
PHP_IV_TOOLCHAIN_TOOLS=(autoconf bison re2c pkg-config)
PHP_IV_CONFIGURE_ARGS=()
PHP_IV_NOTES="Legacy scaffold only. Apple Silicon support remains experimental."
