PHP_IV_TC_COMPONENT="bison-2.7.1"
PHP_IV_TC_KIND="bison"
PHP_IV_TC_NAME="bison"
PHP_IV_TC_VERSION="2.7.1"
PHP_IV_TC_ARCHIVE="bison-2.7.1.tar.xz"
PHP_IV_TC_URL="https://ftp.gnu.org/gnu/bison/bison-2.7.1.tar.xz"
PHP_IV_TC_SOURCE_DIR="bison-2.7.1"
PHP_IV_TC_NOTES="Legacy parser generator toolchain for PHP 5.x."
